from odoo import models, fields

class ProductUom(models.Model):
    _inherit = 'product.uom'

    code = fields.Selection([('Sp ','Servicios Profesionales'),
           ('m ','Metro'),
    ('kg ','Kilogramo'),
    ('s ','Segundo'),
    ('A ','Ampere'),
    ('K ','Kelvin'),
    ('mol ','Mol'),
    ('cd','Candela'),
    ('m²','metro cuadrado'),
    ('m³','metro cúbico'),
    ('m/s','metro por segundo'),
    ('m/s²','metro por segundo cuadrado'),
    ('1/m','1 por metro'),
    ('kg/m³','kilogramo por metro cúbico'),
    ('A/m²','ampere por metro cuadrado'),
    ('A/m','ampere por metro'),
    ('mol/m³','mol por metro cúbico'),
    ('cd/m²','candela por metro cuadrado'),
    ('1','uno (indice de refracción)'),
    ('rad','radián'),
    ('sr','estereorradián'),
    ('Hz','hertz'),
    ('N','newton'),
    ('Pa','pascal'),
    ('J','Joule'),
    ('W','Watt'),
    ('C','coulomb'),
    ('V','volt'),
    ('F','farad'),
    ('Ω','ohm'),
    ('S','siemens'),
    ('Wb','weber'),
    ('T','tesla'),
    ('H','henry'),
    ('°C','grado Celsius'),
    ('lm','lumen'),
    ('lx','lux'),
    ('Bq','Becquerel'),
    ('Gy','gray'),
    ('Sv','sievert'),
    ('kat','katal'),
    ('Pa·s','pascal segundo'),
    ('N·m','newton metro'),
    ('N/m','newton por metro'),
    ('rad/s','radián por segundo'),
    ('rad/s²','radián por segundo cuadrado'),
    ('W/m²','watt por metro cuadrado'),
    ('J/K','joule por kelvin'),
    ('J/(kg·K)','joule por kilogramo kelvin'),
    ('J/kg','joule por kilogramo'),
    ('W/(m·K)','watt por metro kevin'),
    ('J/m³','joule por metro cúbico'),
    ('V/m','volt por metro'),
    ('C/m³','coulomb por metro cúbico'),
    ('C/m²','coulomb por metro cuadrado'),
    ('F/m','farad por metro'),
    ('H/m','henry por metro'),
    ('J/mol','joule por mol'),
    ('J/(mol·K)','joule por mol kelvin'),
    ('C/kg','coulomb por kilogramo'),
    ('Gy/s','gray por segundo'),
    ('W/sr','watt por estereorradián'),
    ('W/(m²·sr)','watt por metro cuadrado estereorradián'),
    ('kat/m³','katal por metro cúbico'),
    ('min','minuto'),
    ('h','hora'),
    ('d','día'),
    ('º','grado'),
    ('´','minuto'),
    ('´´','segundo'),
    ('L','litro'),
    ('t','tonelada'),
    ('Np','neper'),
    ('B','bel'),
    ('eV','electronvolt'),
    ('u','unidad de masa atómica unificada'),
    ('ua','unidad astronómica'),
    ('Unid','Unidad'),
    ('Gal','Galón'),
    ('g','Gramo'),
    ('Km','Kilometro'),
    ('ln','pulgada'),
    ('cm','centímetro'),
    ('mL','mililitro'),
    ('mm','Milímetro'),
    ('Oz','Onzas'),
    ('Otros','Se debe indicar la descripción de la medida a utilizar')], string='Code',default='Unid')